### ISSUE TITLE
Yearn SDK instantiation error handling

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#427]
When making many exits via `exit-commit-tx` on the DAI bonder, the bonder started responding with the following error. This did not cause any functional issues and the exit command continued to work. However, I believe this error should be better handled so that whatever effects happen downstream related to yearn don't break.

``` 
SdkError: HTTP to https://api.github.com/repos/yearn/yearn-assets/contents/icons/multichain-tokens/1 request failed (status 403 rate limit exceeded)
    at _callee$ (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:2672:19)
    at tryCatch (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:507:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:737:22)
    at Generator.next (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:562:21)
    at asyncGeneratorStep (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:21:24)
    at _next (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:43:9)
    at /usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:50:7
    at new Promise (<anonymous>)
    at /usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:39:12
    at handleHttpError (/usr/src/app/node_modules/@yfi/sdk/dist/sdk.cjs.development.js:2656:27) {
  error_type: 'sdk',
  error_code: undefined
}
```

**Comment by miguelmota** [comment]
This is known issue I reported a while back https://github.com/yearn/yearn-sdk/issues/236

but should be resolved now by updating sdk

Closed by https://github.com/hop-protocol/hop/commit/783655e57b23877a24f78c3b5b9d8441f6eb3bd3
